// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmoslottery/lottery/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41809820bea9b710, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41809820bea9b710, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetActiveLotteryRequest struct {
}

func (m *QueryGetActiveLotteryRequest) Reset()         { *m = QueryGetActiveLotteryRequest{} }
func (m *QueryGetActiveLotteryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetActiveLotteryRequest) ProtoMessage()    {}
func (*QueryGetActiveLotteryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41809820bea9b710, []int{2}
}
func (m *QueryGetActiveLotteryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetActiveLotteryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetActiveLotteryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetActiveLotteryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetActiveLotteryRequest.Merge(m, src)
}
func (m *QueryGetActiveLotteryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetActiveLotteryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetActiveLotteryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetActiveLotteryRequest proto.InternalMessageInfo

type QueryGetActiveLotteryResponse struct {
	ActiveLottery ActiveLottery `protobuf:"bytes,1,opt,name=ActiveLottery,proto3" json:"ActiveLottery"`
}

func (m *QueryGetActiveLotteryResponse) Reset()         { *m = QueryGetActiveLotteryResponse{} }
func (m *QueryGetActiveLotteryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetActiveLotteryResponse) ProtoMessage()    {}
func (*QueryGetActiveLotteryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41809820bea9b710, []int{3}
}
func (m *QueryGetActiveLotteryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetActiveLotteryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetActiveLotteryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetActiveLotteryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetActiveLotteryResponse.Merge(m, src)
}
func (m *QueryGetActiveLotteryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetActiveLotteryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetActiveLotteryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetActiveLotteryResponse proto.InternalMessageInfo

func (m *QueryGetActiveLotteryResponse) GetActiveLottery() ActiveLottery {
	if m != nil {
		return m.ActiveLottery
	}
	return ActiveLottery{}
}

type QueryGetLotteryTransactionRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetLotteryTransactionRequest) Reset()         { *m = QueryGetLotteryTransactionRequest{} }
func (m *QueryGetLotteryTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetLotteryTransactionRequest) ProtoMessage()    {}
func (*QueryGetLotteryTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41809820bea9b710, []int{4}
}
func (m *QueryGetLotteryTransactionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLotteryTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLotteryTransactionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLotteryTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLotteryTransactionRequest.Merge(m, src)
}
func (m *QueryGetLotteryTransactionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLotteryTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLotteryTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLotteryTransactionRequest proto.InternalMessageInfo

func (m *QueryGetLotteryTransactionRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetLotteryTransactionResponse struct {
	LotteryTransaction LotteryTransaction `protobuf:"bytes,1,opt,name=LotteryTransaction,proto3" json:"LotteryTransaction"`
}

func (m *QueryGetLotteryTransactionResponse) Reset()         { *m = QueryGetLotteryTransactionResponse{} }
func (m *QueryGetLotteryTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetLotteryTransactionResponse) ProtoMessage()    {}
func (*QueryGetLotteryTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41809820bea9b710, []int{5}
}
func (m *QueryGetLotteryTransactionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLotteryTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLotteryTransactionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLotteryTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLotteryTransactionResponse.Merge(m, src)
}
func (m *QueryGetLotteryTransactionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLotteryTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLotteryTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLotteryTransactionResponse proto.InternalMessageInfo

func (m *QueryGetLotteryTransactionResponse) GetLotteryTransaction() LotteryTransaction {
	if m != nil {
		return m.LotteryTransaction
	}
	return LotteryTransaction{}
}

type QueryAllLotteryTransactionRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllLotteryTransactionRequest) Reset()         { *m = QueryAllLotteryTransactionRequest{} }
func (m *QueryAllLotteryTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllLotteryTransactionRequest) ProtoMessage()    {}
func (*QueryAllLotteryTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41809820bea9b710, []int{6}
}
func (m *QueryAllLotteryTransactionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllLotteryTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllLotteryTransactionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllLotteryTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllLotteryTransactionRequest.Merge(m, src)
}
func (m *QueryAllLotteryTransactionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllLotteryTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllLotteryTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllLotteryTransactionRequest proto.InternalMessageInfo

func (m *QueryAllLotteryTransactionRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllLotteryTransactionResponse struct {
	LotteryTransaction []LotteryTransaction `protobuf:"bytes,1,rep,name=LotteryTransaction,proto3" json:"LotteryTransaction"`
	Pagination         *query.PageResponse  `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllLotteryTransactionResponse) Reset()         { *m = QueryAllLotteryTransactionResponse{} }
func (m *QueryAllLotteryTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllLotteryTransactionResponse) ProtoMessage()    {}
func (*QueryAllLotteryTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41809820bea9b710, []int{7}
}
func (m *QueryAllLotteryTransactionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllLotteryTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllLotteryTransactionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllLotteryTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllLotteryTransactionResponse.Merge(m, src)
}
func (m *QueryAllLotteryTransactionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllLotteryTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllLotteryTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllLotteryTransactionResponse proto.InternalMessageInfo

func (m *QueryAllLotteryTransactionResponse) GetLotteryTransaction() []LotteryTransaction {
	if m != nil {
		return m.LotteryTransaction
	}
	return nil
}

func (m *QueryAllLotteryTransactionResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetLotteryRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetLotteryRequest) Reset()         { *m = QueryGetLotteryRequest{} }
func (m *QueryGetLotteryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetLotteryRequest) ProtoMessage()    {}
func (*QueryGetLotteryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41809820bea9b710, []int{8}
}
func (m *QueryGetLotteryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLotteryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLotteryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLotteryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLotteryRequest.Merge(m, src)
}
func (m *QueryGetLotteryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLotteryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLotteryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLotteryRequest proto.InternalMessageInfo

func (m *QueryGetLotteryRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetLotteryResponse struct {
	Lottery Lottery `protobuf:"bytes,1,opt,name=lottery,proto3" json:"lottery"`
}

func (m *QueryGetLotteryResponse) Reset()         { *m = QueryGetLotteryResponse{} }
func (m *QueryGetLotteryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetLotteryResponse) ProtoMessage()    {}
func (*QueryGetLotteryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41809820bea9b710, []int{9}
}
func (m *QueryGetLotteryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLotteryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLotteryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLotteryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLotteryResponse.Merge(m, src)
}
func (m *QueryGetLotteryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLotteryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLotteryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLotteryResponse proto.InternalMessageInfo

func (m *QueryGetLotteryResponse) GetLottery() Lottery {
	if m != nil {
		return m.Lottery
	}
	return Lottery{}
}

type QueryAllLotteryRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllLotteryRequest) Reset()         { *m = QueryAllLotteryRequest{} }
func (m *QueryAllLotteryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllLotteryRequest) ProtoMessage()    {}
func (*QueryAllLotteryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41809820bea9b710, []int{10}
}
func (m *QueryAllLotteryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllLotteryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllLotteryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllLotteryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllLotteryRequest.Merge(m, src)
}
func (m *QueryAllLotteryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllLotteryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllLotteryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllLotteryRequest proto.InternalMessageInfo

func (m *QueryAllLotteryRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllLotteryResponse struct {
	Lottery    []Lottery           `protobuf:"bytes,1,rep,name=lottery,proto3" json:"lottery"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllLotteryResponse) Reset()         { *m = QueryAllLotteryResponse{} }
func (m *QueryAllLotteryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllLotteryResponse) ProtoMessage()    {}
func (*QueryAllLotteryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41809820bea9b710, []int{11}
}
func (m *QueryAllLotteryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllLotteryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllLotteryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllLotteryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllLotteryResponse.Merge(m, src)
}
func (m *QueryAllLotteryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllLotteryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllLotteryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllLotteryResponse proto.InternalMessageInfo

func (m *QueryAllLotteryResponse) GetLottery() []Lottery {
	if m != nil {
		return m.Lottery
	}
	return nil
}

func (m *QueryAllLotteryResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "cosmoslottery.lottery.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "cosmoslottery.lottery.QueryParamsResponse")
	proto.RegisterType((*QueryGetActiveLotteryRequest)(nil), "cosmoslottery.lottery.QueryGetActiveLotteryRequest")
	proto.RegisterType((*QueryGetActiveLotteryResponse)(nil), "cosmoslottery.lottery.QueryGetActiveLotteryResponse")
	proto.RegisterType((*QueryGetLotteryTransactionRequest)(nil), "cosmoslottery.lottery.QueryGetLotteryTransactionRequest")
	proto.RegisterType((*QueryGetLotteryTransactionResponse)(nil), "cosmoslottery.lottery.QueryGetLotteryTransactionResponse")
	proto.RegisterType((*QueryAllLotteryTransactionRequest)(nil), "cosmoslottery.lottery.QueryAllLotteryTransactionRequest")
	proto.RegisterType((*QueryAllLotteryTransactionResponse)(nil), "cosmoslottery.lottery.QueryAllLotteryTransactionResponse")
	proto.RegisterType((*QueryGetLotteryRequest)(nil), "cosmoslottery.lottery.QueryGetLotteryRequest")
	proto.RegisterType((*QueryGetLotteryResponse)(nil), "cosmoslottery.lottery.QueryGetLotteryResponse")
	proto.RegisterType((*QueryAllLotteryRequest)(nil), "cosmoslottery.lottery.QueryAllLotteryRequest")
	proto.RegisterType((*QueryAllLotteryResponse)(nil), "cosmoslottery.lottery.QueryAllLotteryResponse")
}

func init() { proto.RegisterFile("cosmoslottery/lottery/query.proto", fileDescriptor_41809820bea9b710) }

var fileDescriptor_41809820bea9b710 = []byte{
	// 698 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x73, 0xe9, 0x2f, 0x71, 0x08, 0x86, 0xa3, 0x05, 0x14, 0xb5, 0x6e, 0x7b, 0xa0, 0xa6,
	0x2d, 0x8a, 0x4d, 0x13, 0x86, 0x20, 0x24, 0xa4, 0x74, 0xa0, 0x0b, 0x43, 0xb0, 0x58, 0x60, 0x09,
	0x4e, 0x72, 0xb2, 0x2c, 0x5c, 0x9f, 0x13, 0xbb, 0x55, 0xa3, 0xaa, 0x0b, 0x12, 0x62, 0x45, 0x82,
	0x85, 0x95, 0x91, 0xff, 0x02, 0xb1, 0x74, 0x42, 0x95, 0x58, 0x98, 0x10, 0x4a, 0xf8, 0x2f, 0x58,
	0x50, 0xee, 0x9e, 0x9b, 0x38, 0xfe, 0x91, 0x04, 0x65, 0x72, 0xeb, 0xfb, 0xbe, 0xf7, 0x3e, 0xdf,
	0xe7, 0xe7, 0xe7, 0xe0, 0xcd, 0x06, 0xf7, 0x0e, 0xb9, 0x67, 0x73, 0xdf, 0x67, 0xed, 0x8e, 0x16,
	0x5c, 0x5b, 0x47, 0xac, 0xdd, 0x51, 0xdd, 0x36, 0xf7, 0x39, 0x59, 0x09, 0x49, 0x54, 0xb8, 0xe6,
	0x96, 0x4d, 0x6e, 0x72, 0xa1, 0xd0, 0xfa, 0x7f, 0x49, 0x71, 0x6e, 0xd5, 0xe4, 0xdc, 0xb4, 0x99,
	0x66, 0xb8, 0x96, 0x66, 0x38, 0x0e, 0xf7, 0x0d, 0xdf, 0xe2, 0x8e, 0x07, 0xa7, 0xbb, 0x32, 0x95,
	0x56, 0x37, 0x3c, 0x26, 0x6b, 0x68, 0xc7, 0x7b, 0x75, 0xe6, 0x1b, 0x7b, 0x9a, 0x6b, 0x98, 0x96,
	0x23, 0xc4, 0xa0, 0xa5, 0xf1, 0x64, 0xae, 0xd1, 0x36, 0x0e, 0x47, 0xf2, 0x8d, 0x6a, 0x8c, 0x86,
	0x6f, 0x1d, 0xb3, 0x5a, 0x40, 0x2c, 0xb5, 0x5a, 0xbc, 0x16, 0xae, 0x35, 0xbf, 0x6d, 0x38, 0x5e,
	0x3f, 0xf0, 0x12, 0xe0, 0x4e, 0x6a, 0x00, 0x88, 0x94, 0x61, 0x47, 0x81, 0x97, 0x06, 0xb7, 0x20,
	0x09, 0x5d, 0xc6, 0xe4, 0x59, 0xdf, 0x67, 0x55, 0x60, 0xeb, 0xac, 0x75, 0xc4, 0x3c, 0x9f, 0xea,
	0xf8, 0x46, 0xe8, 0xae, 0xe7, 0x72, 0xc7, 0x63, 0xe4, 0x11, 0x5e, 0x94, 0xf6, 0x6e, 0xa3, 0x0d,
	0xb4, 0x7d, 0xb5, 0xb8, 0xa6, 0xc6, 0xb6, 0x5e, 0x95, 0x61, 0xfb, 0xf3, 0xe7, 0xbf, 0xd6, 0x33,
	0x3a, 0x84, 0x50, 0x05, 0xaf, 0x8a, 0x9c, 0x07, 0xcc, 0xaf, 0x08, 0xff, 0x4f, 0xa5, 0x3a, 0xa8,
	0xd9, 0xc2, 0x6b, 0x09, 0xe7, 0x50, 0xbd, 0x8a, 0xaf, 0x85, 0x0e, 0x00, 0xe2, 0x6e, 0x02, 0x44,
	0x48, 0x0b, 0x2c, 0xe1, 0x04, 0xb4, 0x84, 0x37, 0x83, 0x92, 0x70, 0xeb, 0xf9, 0xa0, 0xcb, 0xc0,
	0x45, 0xae, 0xe3, 0xac, 0xd5, 0x14, 0xb5, 0xe6, 0xf5, 0xac, 0xd5, 0xa4, 0x6f, 0x11, 0xa6, 0x69,
	0x51, 0x40, 0x5b, 0xc3, 0x24, 0x7a, 0x0a, 0xc8, 0x3b, 0x09, 0xc8, 0xd1, 0x00, 0xe0, 0x8e, 0x49,
	0x45, 0x5f, 0x03, 0x7c, 0xc5, 0xb6, 0x93, 0xe1, 0x9f, 0x60, 0x3c, 0x18, 0x5c, 0xa8, 0xbe, 0x05,
	0xd5, 0xd5, 0xfe, 0x4c, 0xa8, 0xf2, 0x4d, 0x82, 0xc9, 0x50, 0xab, 0x86, 0xc9, 0x20, 0x56, 0x1f,
	0x8a, 0xa4, 0xdf, 0x03, 0xd3, 0x09, 0xd5, 0xc6, 0x98, 0x9e, 0x9b, 0x91, 0x69, 0x72, 0x10, 0xf2,
	0x93, 0x15, 0x7e, 0xf2, 0x63, 0xfd, 0x48, 0xba, 0x90, 0x21, 0x15, 0xdf, 0x1c, 0x79, 0x88, 0x41,
	0xcb, 0x96, 0xf1, 0x82, 0xe5, 0x34, 0xd9, 0x89, 0xe8, 0xd6, 0x15, 0x5d, 0xfe, 0x43, 0x5f, 0xe0,
	0x5b, 0x11, 0x3d, 0x98, 0x7e, 0x8c, 0x97, 0xec, 0xd0, 0x44, 0x2a, 0xe9, 0x4e, 0xc1, 0x5e, 0x10,
	0x44, 0x5f, 0x01, 0xca, 0xa0, 0xb5, 0xb3, 0x7e, 0x7a, 0x9f, 0x11, 0xd0, 0x0f, 0x97, 0x88, 0xa3,
	0x9f, 0x9b, 0x9a, 0x7e, 0x66, 0x4f, 0xa4, 0xf8, 0x77, 0x09, 0x2f, 0x08, 0x48, 0xf2, 0x0e, 0xe1,
	0x45, 0xb9, 0x42, 0x48, 0xd2, 0xd0, 0x44, 0x77, 0x56, 0x6e, 0x77, 0x12, 0xa9, 0xac, 0x4b, 0xb7,
	0xde, 0xfc, 0xf8, 0xf3, 0x21, 0xbb, 0x41, 0x14, 0x58, 0xba, 0x85, 0xf8, 0x2d, 0x4e, 0xbe, 0xa0,
	0x91, 0x9d, 0x43, 0x4a, 0x69, 0x55, 0x12, 0x56, 0x5b, 0xee, 0xc1, 0x74, 0x41, 0x00, 0xa9, 0x0a,
	0xc8, 0x6d, 0xb2, 0x95, 0x04, 0x19, 0xfe, 0x8c, 0x90, 0x6f, 0x28, 0xee, 0xed, 0x23, 0xe5, 0x31,
	0xc5, 0x13, 0x97, 0x47, 0xee, 0xe1, 0x7f, 0x44, 0x02, 0x7b, 0x59, 0xb0, 0x17, 0xc9, 0xfd, 0x24,
	0xf6, 0x98, 0xcf, 0x9a, 0x76, 0x6a, 0x35, 0xcf, 0xc8, 0x57, 0x84, 0x57, 0xa2, 0x89, 0x2b, 0xb6,
	0x9d, 0x6e, 0x24, 0x6d, 0x0b, 0xa6, 0x1b, 0x49, 0xdd, 0x68, 0xb4, 0x24, 0x8c, 0x14, 0xc8, 0xbd,
	0x29, 0x8c, 0x90, 0x4f, 0x08, 0x2f, 0x05, 0x03, 0x53, 0x98, 0xac, 0x89, 0x01, 0xaa, 0x3a, 0xa9,
	0x1c, 0xf8, 0x34, 0xc1, 0xb7, 0x43, 0xf2, 0x63, 0xf8, 0xb4, 0x53, 0xb1, 0xc7, 0xce, 0xc8, 0x47,
	0x84, 0x31, 0x24, 0xe9, 0x37, 0xb5, 0x30, 0x59, 0x6b, 0x26, 0xc2, 0x8b, 0x6e, 0x17, 0x9a, 0x17,
	0x78, 0x9b, 0x64, 0x7d, 0x0c, 0xde, 0x7e, 0xf9, 0xbc, 0xab, 0xa0, 0x8b, 0xae, 0x82, 0x7e, 0x77,
	0x15, 0xf4, 0xbe, 0xa7, 0x64, 0x2e, 0x7a, 0x4a, 0xe6, 0x67, 0x4f, 0xc9, 0xbc, 0x54, 0x46, 0x22,
	0x4f, 0x2e, 0x63, 0xfd, 0x8e, 0xcb, 0xbc, 0xfa, 0xa2, 0xf8, 0x21, 0x53, 0xfa, 0x17, 0x00, 0x00,
	0xff, 0xff, 0x7d, 0x52, 0xbe, 0x83, 0x2a, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a ActiveLottery by index.
	ActiveLottery(ctx context.Context, in *QueryGetActiveLotteryRequest, opts ...grpc.CallOption) (*QueryGetActiveLotteryResponse, error)
	// Queries a list of LotteryTransaction items.
	LotteryTransaction(ctx context.Context, in *QueryGetLotteryTransactionRequest, opts ...grpc.CallOption) (*QueryGetLotteryTransactionResponse, error)
	LotteryTransactionAll(ctx context.Context, in *QueryAllLotteryTransactionRequest, opts ...grpc.CallOption) (*QueryAllLotteryTransactionResponse, error)
	// Queries a list of Lottery items.
	Lottery(ctx context.Context, in *QueryGetLotteryRequest, opts ...grpc.CallOption) (*QueryGetLotteryResponse, error)
	LotteryAll(ctx context.Context, in *QueryAllLotteryRequest, opts ...grpc.CallOption) (*QueryAllLotteryResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/cosmoslottery.lottery.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ActiveLottery(ctx context.Context, in *QueryGetActiveLotteryRequest, opts ...grpc.CallOption) (*QueryGetActiveLotteryResponse, error) {
	out := new(QueryGetActiveLotteryResponse)
	err := c.cc.Invoke(ctx, "/cosmoslottery.lottery.Query/ActiveLottery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LotteryTransaction(ctx context.Context, in *QueryGetLotteryTransactionRequest, opts ...grpc.CallOption) (*QueryGetLotteryTransactionResponse, error) {
	out := new(QueryGetLotteryTransactionResponse)
	err := c.cc.Invoke(ctx, "/cosmoslottery.lottery.Query/LotteryTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LotteryTransactionAll(ctx context.Context, in *QueryAllLotteryTransactionRequest, opts ...grpc.CallOption) (*QueryAllLotteryTransactionResponse, error) {
	out := new(QueryAllLotteryTransactionResponse)
	err := c.cc.Invoke(ctx, "/cosmoslottery.lottery.Query/LotteryTransactionAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Lottery(ctx context.Context, in *QueryGetLotteryRequest, opts ...grpc.CallOption) (*QueryGetLotteryResponse, error) {
	out := new(QueryGetLotteryResponse)
	err := c.cc.Invoke(ctx, "/cosmoslottery.lottery.Query/Lottery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LotteryAll(ctx context.Context, in *QueryAllLotteryRequest, opts ...grpc.CallOption) (*QueryAllLotteryResponse, error) {
	out := new(QueryAllLotteryResponse)
	err := c.cc.Invoke(ctx, "/cosmoslottery.lottery.Query/LotteryAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a ActiveLottery by index.
	ActiveLottery(context.Context, *QueryGetActiveLotteryRequest) (*QueryGetActiveLotteryResponse, error)
	// Queries a list of LotteryTransaction items.
	LotteryTransaction(context.Context, *QueryGetLotteryTransactionRequest) (*QueryGetLotteryTransactionResponse, error)
	LotteryTransactionAll(context.Context, *QueryAllLotteryTransactionRequest) (*QueryAllLotteryTransactionResponse, error)
	// Queries a list of Lottery items.
	Lottery(context.Context, *QueryGetLotteryRequest) (*QueryGetLotteryResponse, error)
	LotteryAll(context.Context, *QueryAllLotteryRequest) (*QueryAllLotteryResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ActiveLottery(ctx context.Context, req *QueryGetActiveLotteryRequest) (*QueryGetActiveLotteryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActiveLottery not implemented")
}
func (*UnimplementedQueryServer) LotteryTransaction(ctx context.Context, req *QueryGetLotteryTransactionRequest) (*QueryGetLotteryTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LotteryTransaction not implemented")
}
func (*UnimplementedQueryServer) LotteryTransactionAll(ctx context.Context, req *QueryAllLotteryTransactionRequest) (*QueryAllLotteryTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LotteryTransactionAll not implemented")
}
func (*UnimplementedQueryServer) Lottery(ctx context.Context, req *QueryGetLotteryRequest) (*QueryGetLotteryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lottery not implemented")
}
func (*UnimplementedQueryServer) LotteryAll(ctx context.Context, req *QueryAllLotteryRequest) (*QueryAllLotteryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LotteryAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmoslottery.lottery.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ActiveLottery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetActiveLotteryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ActiveLottery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmoslottery.lottery.Query/ActiveLottery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ActiveLottery(ctx, req.(*QueryGetActiveLotteryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LotteryTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetLotteryTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LotteryTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmoslottery.lottery.Query/LotteryTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LotteryTransaction(ctx, req.(*QueryGetLotteryTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LotteryTransactionAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllLotteryTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LotteryTransactionAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmoslottery.lottery.Query/LotteryTransactionAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LotteryTransactionAll(ctx, req.(*QueryAllLotteryTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Lottery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetLotteryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Lottery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmoslottery.lottery.Query/Lottery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Lottery(ctx, req.(*QueryGetLotteryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LotteryAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllLotteryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LotteryAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmoslottery.lottery.Query/LotteryAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LotteryAll(ctx, req.(*QueryAllLotteryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmoslottery.lottery.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ActiveLottery",
			Handler:    _Query_ActiveLottery_Handler,
		},
		{
			MethodName: "LotteryTransaction",
			Handler:    _Query_LotteryTransaction_Handler,
		},
		{
			MethodName: "LotteryTransactionAll",
			Handler:    _Query_LotteryTransactionAll_Handler,
		},
		{
			MethodName: "Lottery",
			Handler:    _Query_Lottery_Handler,
		},
		{
			MethodName: "LotteryAll",
			Handler:    _Query_LotteryAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmoslottery/lottery/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetActiveLotteryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetActiveLotteryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetActiveLotteryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetActiveLotteryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetActiveLotteryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetActiveLotteryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ActiveLottery.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetLotteryTransactionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLotteryTransactionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLotteryTransactionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetLotteryTransactionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLotteryTransactionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLotteryTransactionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.LotteryTransaction.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllLotteryTransactionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllLotteryTransactionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllLotteryTransactionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllLotteryTransactionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllLotteryTransactionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllLotteryTransactionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.LotteryTransaction) > 0 {
		for iNdEx := len(m.LotteryTransaction) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LotteryTransaction[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetLotteryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLotteryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLotteryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetLotteryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLotteryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLotteryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Lottery.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllLotteryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllLotteryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllLotteryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllLotteryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllLotteryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllLotteryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Lottery) > 0 {
		for iNdEx := len(m.Lottery) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Lottery[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetActiveLotteryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetActiveLotteryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ActiveLottery.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetLotteryTransactionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetLotteryTransactionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.LotteryTransaction.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllLotteryTransactionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllLotteryTransactionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.LotteryTransaction) > 0 {
		for _, e := range m.LotteryTransaction {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetLotteryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetLotteryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Lottery.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllLotteryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllLotteryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Lottery) > 0 {
		for _, e := range m.Lottery {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetActiveLotteryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetActiveLotteryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetActiveLotteryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetActiveLotteryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetActiveLotteryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetActiveLotteryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveLottery", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ActiveLottery.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLotteryTransactionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLotteryTransactionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLotteryTransactionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLotteryTransactionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLotteryTransactionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLotteryTransactionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LotteryTransaction", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LotteryTransaction.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllLotteryTransactionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllLotteryTransactionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllLotteryTransactionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllLotteryTransactionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllLotteryTransactionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllLotteryTransactionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LotteryTransaction", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LotteryTransaction = append(m.LotteryTransaction, LotteryTransaction{})
			if err := m.LotteryTransaction[len(m.LotteryTransaction)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLotteryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLotteryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLotteryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLotteryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLotteryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLotteryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lottery", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Lottery.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllLotteryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllLotteryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllLotteryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllLotteryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllLotteryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllLotteryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lottery", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Lottery = append(m.Lottery, Lottery{})
			if err := m.Lottery[len(m.Lottery)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
