version: 1
build:
  main: cmd/cosmos-lotteryd
  binary: cosmos-lotteryd
accounts:
- name: alice
  coins:
    - 500ltry
    - 200000000stake
- name: client1
  coins:
    - 500ltry
    - 200000000stake
- name: client2
  coins:
    - 500ltry
    - 200000000stake
- name: client3
  coins:
    - 500ltry
    - 200000000stake
- name: client4
  coins:
    - 500ltry
    - 200000000stake
- name: client5
  coins:
    - 500ltry
    - 200000000stake
- name: client6
  coins:
    - 500ltry
    - 200000000stake
- name: client7
  coins:
    - 500ltry
    - 200000000stake
- name: client8
  coins:
    - 500ltry
    - 200000000stake
- name: client9
  coins:
    - 500ltry
    - 200000000stake
- name: client10
  coins:
    - 500ltry
    - 200000000stake
- name: client11
  coins:
    - 500ltry
    - 200000000stake
- name: client12
  coins:
    - 500ltry
    - 200000000stake
- name: client13
  coins:
    - 500ltry
    - 200000000stake
- name: client14
  coins:
    - 500ltry
    - 200000000stake
- name: client15
  coins:
    - 500ltry
    - 200000000stake
- name: client16
  coins:
    - 500ltry
    - 200000000stake
- name: client17
  coins:
    - 500ltry
    - 200000000stake
- name: client18
  coins:
    - 500ltry
    - 200000000stake
- name: client19
  coins:
    - 500ltry
    - 200000000stake
- name: client20
  coins:
    - 500ltry
    - 200000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: alice
  coins:
  - 5token
  - 100000stake
genesis:
  app_state:
    lottery:
      activeLottery:
        lotteryId: "2"
      lotteryList:
        - fee:
            amount: "5"
            denom: "ltry"
          index: "1"
          pool:
            amount: "390"
            denom: "ltry"
          winner: "cosmos1z7nnsdjs4v4fm5ryf0cxqu08tpjpvx26kk4xyx"
        - fee:
            amount: "5"
            denom: "ltry"
          index: "2"
          pool:
            amount: "0"
            denom: "ltry"
          winner: ""
validators:
- name: alice
  bonded: 100000000stake
  config:
    consensus:
      timeout_commit: "300s"
